public class CalculateC {
//public static integer a=15;
   /* public static decimal ucgenAlan(decimal t,decimal h){
    decimal alan=(t*h)/2;
        system.debug('Metod Alan Sonuc: '+alan);
        return alan;
    }*/
   /* public static void DikdortgenA (integer x, integer y){
        integer a=x*y;
        //system.debug('Dikdortgen Alani: '+a);
    }
    public static string Profil(string n){
        string isim ='Hello '+n;
        return isim;
    } 
    public static void Profil2(string m){
        string name='Hello'+m;
        system.debug(name);
    }*/
    public static void MesajKontrol(integer s,string mesaj){
        for (integer i=1;i<=s;i++){
            system.debug('Hello '+mesaj);
        }
    }
    
    
}