public class Process {
    public static void Sum (integer one , integer two){
        system.debug(one+two);
    }
    
    public static void Sub (integer a , integer b){
        system.debug(a-b);
      }
    
    public static integer Mul(integer x,integer y){
        integer result=x*y;
        return result;
    }
    public static decimal Div(decimal c,decimal d){
        decimal result2=c/d;
        return result2;
    }
    
    public static integer PasswordKontrol(string pass){
        integer sonuc3 = pass.length();
        return sonuc3;
    }
      
}